@echo off

:: generated by online generation tool, and it sucks
set java=false
set bedrock=false
if defined "%~1" (
  set javafolder="%~1"
  set bedrockfolder="%~1"
  goto :endosdir
)
set javafolder="%appdata%\.minecraft"
set bedrockfolder="%localappdata%\packages\microsoft.minecraftuwp_8wekyb3d8bbwe\localstate\games\com.mojang"
:endosdir
call :dircheck "%@%"
echo "{\"java\":%java%,\"bedrock\":%bedrock%,\"javafolder\":\"%javafolder%\",\"bedrockfolder\":\"%bedrockfolder%\",\"javaworlds\":\"%javaworlds%\",\"bedrockworlds\":\"%bedrockworlds%\",\"jlauncher\":\"%jlauncher%\"}"

exit /b %errorlevel%

:mmcfind
for /d %%d in ('dir "%~1" /b /ad multimc ultimmc polymc manymc prismlauncher minecraft .minecraft /s') do (
  for /f %%f in ('dir "%%d" /b /ad multimc.cfg ultimmc.cfg polymc.cfg manymc.cfg prismlauncher.cfg launcher_profiles.json /s') do (
    set "%~1 = %%f"
    goto :endfind
  )
)
:endfind
exit /b 0

:mmc
set multimc="%undefined% -printf '%h\n' 2>\dev\null | sort -u | head -1)"
if [[ ! -z "%multimc%" ]] (
  set java=true
  set javafolder="%multimc%"
  set jlauncher=multimc
  set javaworlds="%undefined%\saves"
  [[ "%javaworlds%" == \saves ]] && set javaworlds="%multimc%\instances\1.14.4\saves"
) else (
  set javafolder=
)
exit /b 0

:bedfind
set beddir="%undefined%"
if [[ ! -z "%beddir%" ]] (
  set bedrock=true
  set bedrockfolder="%beddir%"
  set bedrockworlds="%bedrockfolder%\minecraftworlds"
) else (
  set bedrockfolder=
)
exit /b 0

:mmc
set multimc="%undefined%"
[[ "-z" "%multimc%" && "$1" == "darwin" "]]" && set multimc="%undefined%"
[[ "-z" "%multimc%" && "$1" == "darwin" "]]" && set multimc="%undefined%"
set javafolder="%multimc%"
call :dircheck "%~1"
exit /b 0

:bedfind
set beddir="%undefined%"
if [[ "!" "-z" "%beddir%" "]]" (
  set bedrock=true
  set bedrockfolder="%beddir%"
  set bedrockworlds="%bedrockfolder%\minecraftworlds"
) else (
  set bedrockfolder=
)
exit /b 0

:dircheck
if [[ "-d" "%javafolder%" "]]" (
  if [[ "-d" "%javafolder%\home" "]]" (
    set jlauncher=tl
    set dir="%undefined%"
    [[ "!" "-z" "%dir%" "]]" && set javaworlds="%dir%\saves" || set javaworlds="%javafolder%\home\1.14\saves"
    mkdir "-p" "%javaworlds%"
  ) else (
    if [[ "-d" "%javafolder%\instances" "]]" (
      set jlauncher=multimc
      set dir="%undefined%"
      [[ "!" "-z" "%dir%" "]]" && set javaworlds="%dir%\saves" || set javaworlds="%javafolder%\instances\1.14.4\%cd%minecraft\saves"
      mkdir "-p" "%javaworlds%"
    ) else (
      set jlauncher=default
      set javaworlds="%javafolder%\saves"
    )
  )
  if [[ "-d" "%javaworlds%" "]]" (
    set java=true
  ) else (
    set javaworlds=
    [[ "-z" "%~2" "]]" && call :mmc "%~1"
  )
) else (
  if [[ "-z" "%~2" "]]" (
    call :mmc "%~1"
  ) else (
    set javafolder=
  )
)
if [[ "-d" "%bedrockfolder%" "]]" (
  set bedrockworlds="%bedrockfolder%\minecraftworlds"
  if [[ "-d" "%bedrockworlds%" "]]" (
    set bedrock=true
  ) else (
    set bedrockworlds=
    [[ "-z" "%~2" "]]" && call :bedfind
  )
) else (
  if [[ "-z" "%~2" "]]" (
    call :bedfind
  ) else (
    set bedrockfolder=
  )
)
exit /b 0
