@echo off

REM generated by online generation tool, and it sucks
SET java=false
SET bedrock=false
CALL :osdir "%@%"
CALL :dircheck "%@%"
echo "{\"java\":%java%,\"bedrock\":%bedrock%,\"javaFolder\":\"%javaFolder%\",\"bedrockFolder\":\"%bedrockFolder%\",\"javaWorlds\":\"%javaWorlds%\",\"bedrockWorlds\":\"%bedrockWorlds%\",\"JLauncher\":\"%JLauncher%\"}"

EXIT /B %ERRORLEVEL%

:osdir
IF defined "%~1" (
  SET javaFolder="%~1"
  SET bedrockFolder="%~1"
  GOTO :EOF
)
SET javaFolder=%APPDATA%\.minecraft
SET bedrockFolder=%localappdata%\Packages\Microsoft.MinecraftUWP_8wekyb3d8bbwe\LocalState\games\com.mojang
EXIT /B 0

:mmcFind
FOR /D %%D IN ('dir "%~1" /b /ad multimc ultimmc polymc /s') DO
  FOR /D %%F IN ('dir "%%B" /b /ad multimc.cfg ultimmc.cfg polymc.cfg /s') DO
    echo %%F
    GOTO :EOF
  GOTO :EOF
GOTO :EOF
EXIT /B 0

:mmc
SET multimc="%undefined% -printf '%h\n' 2>\dev\null | sort -u | head -1)"
IF [[ ! -z "%multimc%" ]] (
  SET java=true
  SET javaFolder="%multimc%"
  SET JLauncher=multimc
  SET javaWorlds="%undefined%\saves"
  [[ "%javaWorlds%" == \saves ]] && SET javaWorlds="%multimc%\instances\1.14.4\saves"
) ELSE (
  SET javaFolder=
)
EXIT /B 0

:bedfind
SET beddir="%undefined%"
IF [[ ! -z "%beddir%" ]] (
  SET bedrock=true
  SET bedrockFolder="%beddir%"
  SET bedrockWorlds="%bedrockFolder%\minecraftWorlds"
) ELSE (
  SET bedrockFolder=
)
EXIT /B 0

:mmc
SET multimc="%undefined%"
[[ "-z" "%multimc%" && "$1" == "Darwin" "]]" && SET multimc="%undefined%"
[[ "-z" "%multimc%" && "$1" == "Darwin" "]]" && SET multimc="%undefined%"
SET javaFolder="%multimc%"
CALL :dircheck "%~1"
EXIT /B 0

:bedfind
SET beddir="%undefined%"
IF [[ "!" "-z" "%beddir%" "]]" (
  SET bedrock=true
  SET bedrockFolder="%beddir%"
  SET bedrockWorlds="%bedrockFolder%\minecraftWorlds"
) ELSE (
  SET bedrockFolder=
)
EXIT /B 0

:dircheck
IF [[ "-d" "%javaFolder%" "]]" (
  IF [[ "-d" "%javaFolder%\home" "]]" (
    SET JLauncher=tl
    SET dir="%undefined%"
    [[ "!" "-z" "%dir%" "]]" && SET javaWorlds="%dir%\saves" || SET javaWorlds="%javaFolder%\home\1.14\saves"
    mkdir "-p" "%javaWorlds%"
  ) ELSE (
    IF [[ "-d" "%javaFolder%\instances" "]]" (
      SET JLauncher=multimc
      SET dir="%undefined%"
      [[ "!" "-z" "%dir%" "]]" && SET javaWorlds="%dir%\saves" || SET javaWorlds="%javaFolder%\instances\1.14.4\%CD%minecraft\saves"
      mkdir "-p" "%javaWorlds%"
    ) ELSE (
      SET JLauncher=default
      SET javaWorlds="%javaFolder%\saves"
    )
  )
  IF [[ "-d" "%javaWorlds%" "]]" (
    SET java=true
  ) ELSE (
    SET javaWorlds=
    [[ "-z" "%~2" "]]" && CALL :mmc "%~1"
  )
) ELSE (
  IF [[ "-z" "%~2" "]]" (
    CALL :mmc "%~1"
  ) ELSE (
    SET javaFolder=
  )
)
IF [[ "-d" "%bedrockFolder%" "]]" (
  SET bedrockWorlds="%bedrockFolder%\minecraftWorlds"
  IF [[ "-d" "%bedrockWorlds%" "]]" (
    SET bedrock=true
  ) ELSE (
    SET bedrockWorlds=
    [[ "-z" "%~2" "]]" && CALL :bedfind
  )
) ELSE (
  IF [[ "-z" "%~2" "]]" (
    CALL :bedfind
  ) ELSE (
    SET bedrockFolder=
  )
)
EXIT /B 0