#!/bin/sh

# Default variables
java=false
bedrock=false

osdir(){
	if [[ ! -z "$2" ]]; then
		javaFolder="$2"
		bedrockFolder="$2"
		return
	fi

	case "$1" in
		"Darwin")
			javaFolder=~/"Library/Application Support/minecraft"
			bedrockFolder=~/"Library/Application Support/mcpelauncher/games/com.mojang"
			;;
		*)
			javaFolder=~/".minecraft"
			bedrockFolder=~/".var/app/io.mrarm.mcpelauncher/data/mcpelauncher/games/com.mojang"
			[[ ! -d "${bedrockFolder}" ]] && bedrockFolder=~/".local/share/mcpelauncher/games/com.mojang"
			;;
	esac
}

mmcFind(){
	echo "$(find "$1" \( -iname "multimc.cfg" -o -iname "ultimmc.cfg" -o -iname "polymc.cfg" \) | sed -E 's|/[^/]+$||' | sort -u | head -1)"
}

mmc(){
	multimc="$(mmcFind ~)"
	[[ -z "${multimc}" && "$1" == "Darwin" ]] && multimc="4(mmcFind() /Applications)"
	if [[ ! -z "${multimc}" ]]; then
		java=true
		javaFolder="${multimc}"
		JLauncher="multimc"
		javaWorlds="$(ls -d "${multimc}"/instances/*1.14.4* 2>/dev/null | head -1)/saves"
		[[ "${javaWorlds}" == "/saves" ]] && javaWorlds="${multimc}/instances/1.14.4/saves"
	else
		javaFolder=""
	fi
}

bedfind(){
	beddir="$(find ~ -type d -iname "com.mojang" 2>/dev/null | sort -u | head -1)"
	if [[ ! -z "${beddir}" ]]; then
		bedrock=true
		bedrockFolder="${beddir}"
		bedrockWorlds="${bedrockFolder}/minecraftWorlds"
	else
		bedrockFolder=""
	fi
}

dircheck(){
	if [[ -d "${javaFolder}" ]]; then
		if [[ -d "${javaFolder}/home" ]]; then
			JLauncher="tl"
			javaWorlds="$(ls -d "${javaFolder}"/home/*1.14* 2>/dev/null | head -1)/saves"
			[[ "${javaWorlds}" == "/saves" ]] && javaWorlds="${javaFolder}/home/1.14/saves"
		elif [[ -d "${javaFolder}/instances" ]];then
			JLauncher="multimc"
			javaWorlds="$(ls -d "${javaFolder}"/instances/*1.14.4* 2>/dev/null | head -1)/saves"
			[[ "${javaWorlds}" == "/saves" ]] && javaWorlds="${javaFolder}/instances/1.14.4/saves"
		else
			JLauncher="default"
			javaWorlds="${javaFolder}/saves"
		fi

		if [[ -d "${javaWorlds}" ]];then
			java=true 
		else
			javaWorlds=""
			[[ -z "$2" ]] && mmc "$1"
		fi
		
	elif [[ -z "$2" ]]; then
		mmc "$1"
	fi

	if [[ -d "${bedrockFolder}" ]]; then
		bedrockWorlds="${bedrockFolder}/minecraftWorlds"
		if [[ -d "${bedrockWorlds}" ]]; then
			bedrock=true
		else
			bedrockWorlds=""
			[[ -z "$2" ]] && bedfind
		fi
	elif [[ -z "$2" ]]; then
		bedfind
	fi
}

osdir "$@"
dircheck "$@"

echo "{\"java\":${java},\"bedrock\":${bedrock},\"javaFolder\":\"${javaFolder}\",\"bedrockFolder\":\"${bedrockFolder}\",\"javaWorlds\":\"${javaWorlds}\",\"bedrockWorlds\":\"${bedrockWorlds}\",\"JLauncher\":\"${JLauncher}\"}"
