@echo off

REM generated by online generation tool, and it sucks
SET java=false
SET bedrock=false
CALL :osdir "%@%"
CALL :dircheck "%@%"
echo "{\"java\":%java%,\"bedrock\":%bedrock%,\"javaFolder\":\"%javaFolder%\",\"bedrockFolder\":\"%bedrockFolder%\",\"javaWorlds\":\"%javaWorlds%\",\"bedrockWorlds\":\"%bedrockWorlds%\",\"JLauncher\":\"%JLauncher%\"}"

EXIT /B %ERRORLEVEL%

:osdir
IF [[ ! -z "%~1" ]] (
  SET javaFolder="%~1"
  SET bedrockFolder="%~1"
  return
)
SET javaFolder=%APPDATA%\%CD%minecraft
SET bedrockFolder=%localappdata%\Packages\Microsoft.MinecraftUWP_8wekyb3d8bbwe\LocalState\games\com.mojang
EXIT /B 0

:mmc
SET multimc="%undefined% -printf '%h\n' 2>\dev\null | sort -u | head -1)"
IF [[ ! -z "%multimc%" ]] (
  SET java=true
  SET javaFolder="%multimc%"
  SET JLauncher=multimc
  SET javaWorlds="%undefined%\saves"
  [[ "%javaWorlds%" == \saves ]] && SET javaWorlds="%multimc%\instances\1.14.4\saves"
) ELSE (
  SET javaFolder=
)
EXIT /B 0

:bedfind
SET beddir="%undefined%"
IF [[ ! -z "%beddir%" ]] (
  SET bedrock=true
  SET bedrockFolder="%beddir%"
  SET bedrockWorlds="%bedrockFolder%\minecraftWorlds"
) ELSE (
  SET bedrockFolder=
)
EXIT /B 0

:dircheck
IF [[ -d "%javaFolder%" ]] (
  IF [[ -d "%javaFolder%\home" ]] (
    SET JLauncher=tl
    SET javaWorlds="%undefined%\saves"
    [[ "%javaWorlds%" == \saves ]] && SET javaWorlds="%javaFolder%\home\1.14\saves"
  ) ELSE (
    IF [[ -d "%javaFolder%\instances" ]] (
      SET JLauncher=multimc
      SET javaWorlds="%undefined%\saves"
      [[ "%javaWorlds%" == \saves ]] && SET javaWorlds="%javaFolder%\instances\1.14.4\saves"
    ) ELSE (
      SET JLauncher=default
      SET javaWorlds="%javaFolder%\saves"
    )
  )
  IF [[ -d "%javaWorlds%" ]] (
    SET java=true
  ) ELSE (
    SET javaWorlds=
    [[ -z "%~1" ]] && CALL :mmc
  )
) ELSE (
  IF [[ -z "%~1" ]] (
    CALL :mmc
  )
)
IF [[ -d "%bedrockFolder%" ]] (
  SET bedrockWorlds="%bedrockFolder%\minecraftWorlds"
  IF [[ -d "%bedrockWorlds%" ]] (
    SET bedrock=true
  ) ELSE (
    SET bedrockWorlds=
    [[ -z "%~1" ]] && CALL :bedfind
  )
) ELSE (
  IF [[ -z "%~1" ]] (
    CALL :bedfind
  )
)
EXIT /B 0